### ISSUE TITLE
CS50 IDE is not uploading

### ISSUE THREAD

**Issue by OpenPier** [cs50/v4-issues#10]
#### What steps did you follow to reproduce the problem?
1. step 1
1. step 2
1. step 3

**Comment by kzidane** [comment]
Could you be more specific please? What symptoms are you seeing exactly and what steps did you follow to cause the problem?

**Comment by OpenPier** [comment]
I went continued to work on the ide and the link shut me out.

**Comment by kzidane** [comment]
Did you try reloading the page or visiting https://ide.cs50.io/ again?

**Comment by OpenPier** [comment]
https://ide.cs50.io/ is not allowing me to go into the IDE.

**Comment by OpenPier** [comment]
I tried safari and chrome and opera and all three are failing to connect.

**Comment by kzidane** [comment]
Could you post a screenshot of the issue you're seeing please?


Kareem

**Comment by OpenPier** [comment]
<img width="800" alt="screen shot 2019-03-07 at 3 16 08 pm" src="https://user-images.githubusercontent.com/35052947/53989654-1036d800-40ec-11e9-8f71-ff8092a8a352.png">

**Comment by kzidane** [comment]
Are you by any chance signed into the AWS console? If yes, can you try logging out or clicking on https://console.aws.amazon.com/console/logout!doLogout and trying again? If no, do you have any adblocker installed?

**Comment by OpenPier** [comment]
I do not have an AWS account. I did sign out of my Amazon account. Still no results.

**Comment by OpenPier** [comment]
![screen shot 2019-03-07 at 3 31 40 pm](https://user-images.githubusercontent.com/35052947/53990588-378ea480-40ee-11e9-8704-34a28ac50061.png)

**Comment by OpenPier** [comment]
Is there anything else I can do. I have to submit my work tonight.

**Comment by kzidane** [comment]
Did you say you had an adblocker installed? If so, can you disable that and
try again?


Kareem

**Comment by OpenPier** [comment]
I tried. It's still not working.

**Comment by kzidane** [comment]
What if you try in incognito mode on chrome or private mode on firefox?


Kareem

**Comment by OpenPier** [comment]
I just tried it. It was not successful.

**Comment by kzidane** [comment]
If you open Chrome's dev console by pressing Ctrl (or Cmd)+Shift+J, do you
see any errors? Can you paste them here if so?


Kareem

**Comment by OpenPier** [comment]
![screen shot 2019-03-07 at 4 19 36 pm](https://user-images.githubusercontent.com/35052947/53993377-dcac7b80-40f4-11e9-8c42-1155b6864924.png)

**Comment by OpenPier** [comment]
I don't have an AWS account. This is really odd.

**Comment by kzidane** [comment]
Do you happen to have team viewer installed or wouldn't mind installing it
so that I can take a closer look?


Kareem

**Comment by OpenPier** [comment]
What is team viewer? I would not mind installing it.

**Comment by kzidane** [comment]
It's a tool that would allow for sharing your screen with me and for me me
to remotely interact with it. See https://teamviewer.com/. One you download
and install, you can email me your ID and temporary password.


Kareem

**Comment by OpenPier** [comment]
okay. I downloaded it. 
user: 1 212 086 046
password: 1i7w1s

**Comment by kzidane** [comment]
You had third-party cookies disabled and that was the cause of the issue.

**Comment by OpenPier** [comment]
It works now?

**Comment by OpenPier** [comment]
Awesome. Thank you Kareem!
