### ISSUE TITLE
Issues while logging in with github

### ISSUE THREAD

**Issue by nathswastik** [cs50/v4-issues#11]
#### What symptom did you see (attaching screenshots as necessary)?

When trying to logging in into the CS50 IDE V4 with GitHub auth, it returns a 403 forbidden error

> Forbidden
> You don't have the permission to access the requested resource. It is either read-protected or not readable by the server.

the link it redirected to is: https://ide.cs50.io/redirect_uri?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&state=ZRNIeYcSLHIMpQXBBVCs0WVEBlNhC4

#### When date and time (UTC) did the problem happen?

8:48 am
Wednesday, 27 March 2019
Coordinated Universal Time (UTC) 

#### What steps did you follow to reproduce the problem?
1. step 1
Go to https://ide.cs50.io/
2. step 2
click on "sign-in with github"
3. step 3
Error login page

#### Which web browser did you use (including version number)?
Chrome-latest
Firefox-Latest

#### Which operating system did you use (including version number)?
Windows-10

#### Did you log in to CS50 IDE using the same GitHub account you used to create this issue?
Yes

**Comment by kzidane** [comment]
Sorry for the troubles! Should be fixed now. Please comment if you're still facing the issue!

**Comment by nathswastik** [comment]
It logs in fine now, after that the preparing environment page comes and after that it goes into a blank page
![blank](https://user-images.githubusercontent.com/44782981/55072878-48f61b80-50b2-11e9-9414-4d5dd74afd6e.png)

**Comment by kzidane** [comment]
Do you see any errors in the JavaScript console? You should be able to bring that up on Firefox by pressing Ctrl + Shift + J on your keyboard.

**Comment by nathswastik** [comment]
Okay, I see some errors. It looks like my browser is blocking some cookies, I allowed all cookies in browser settings and everything is back to normal. Thanks for your help.

P.S: However, it looks like something has changed recently, I have used v4 cs50 ide in firefox before and I had never blocked cookies from https://ide.cs50.io
