### ISSUE TITLE
Failed to start workspace

### ISSUE THREAD

**Issue by picklu** [cs50/v4-issues#15]
#### What symptom did you see (attaching screenshots as necessary)?
![cs50ide_error_loading](https://user-images.githubusercontent.com/4954710/56452351-99882e00-636b-11e9-9529-5c640eb0c13f.png)

#### When date and time (UTC) did the problem happen?
3:45 AM Saturday, April 20, 2019

#### What steps did you follow to reproduce the problem?
1. step 1: During sign in with GitHub id.

#### Which web browser did you use (including version number)?
Chrome

#### Which operating system did you use (including version number)?
Windows 10

#### Did you login to CS50 IDE using the same GitHub account you used to create this issue?
Yes, I used the same GitHub account.

**Comment by kzidane** [comment]
Try again now?

**Comment by picklu** [comment]
Now it shows "signin.aws.amazon.com refused to connect."
![Untitled](https://user-images.githubusercontent.com/4954710/56453673-d3176400-6380-11e9-9339-d8ebafa67214.png)

**Comment by kzidane** [comment]
Do you have an adblocker or third-party cookies disabled? Can you try in incognito mode or firefox?

**Comment by picklu** [comment]
Yes, it works in incognito mode.

**Comment by kzidane** [comment]
I suggest you whitelist the IDE in your adblocker or enable third-party cookies if they're disabled then.
