### ISSUE TITLE
IDE times out frequently

### ISSUE THREAD

**Issue by SNathJr** [cs50/v4-issues#17]
#### What symptom did you see (attaching screenshots as necessary)?

CS50 IDE keeps timing out when I am following with the lecture videos. If I keep it on idle for about 20 - 30 minutes. I get logged out of the IDE.

#### When date and time (UTC) did the problem happen?

5:21 am
Friday, 3 May 2019
Coordinated Universal Time (UTC)

#### What steps did you follow to reproduce the problem?
1. step 1 :Start the ide during a lecture

2. step 2: wait for 20 - 30 minutes

3. step 3: IDE asks to return to dashboard

#### Which web browser did you use (including version number)?

Chrome

#### Which operating system did you use (including version number)?

Windows 10

#### Did you log in to CS50 IDE using the same GitHub account you used to create this issue?

Yes

**Comment by SNathJr** [comment]
Hi @kzidane 

I noticed, the new cs50 ide has a default time out feature of 30 minutes. No matter what I do, I seem unable to increase that limit. A 2 hour limit, just like the legacy IDE would be very nice.

Thanks!

**Comment by kzidane** [comment]
We will increase this timeout in the near future.

**Comment by SNathJr** [comment]
Hi @kzidane, Thanks! Looking forward to have this feature.

**Comment by kzidane** [comment]
This should be increased now!

**Comment by bennetsong08** [comment]
im getting logged out every 5-10 minutes, even when im active, what do i do?

**Comment by kzidane** [comment]
@bobdalobster can you please elaborate more and perhaps include a screenshot of the error?

**Comment by bennetsong08** [comment]
oh its fixed now thx

________________________________
