### ISSUE TITLE
Web-Server Link Still Doesn't Seem to Work

### ISSUE THREAD

**Issue by sgilbert-student** [cs50/v4-issues#19]
#### What symptom did you see (attaching screenshots as necessary)?
The CS50 Web app "welcome page" appears when you first select the Web server. If you click the button, it shows a bad gateway. 

#### When date and time (UTC) did the problem happen?
Thu May  9 20:48:58 UTC 2019

#### What steps did you follow to reproduce the problem?
Here are screenshots:
![image](https://user-images.githubusercontent.com/36554337/57485707-4ebe4f80-7261-11e9-8b3d-24f087e14b39.png)

![image](https://user-images.githubusercontent.com/36554337/57485729-58e04e00-7261-11e9-8ace-56d9199b76d3.png)

![image](https://user-images.githubusercontent.com/36554337/57485740-63024c80-7261-11e9-8ed9-557b879d87fc.png)

#### Which web browser did you use (including version number)?
Firefox 66.0.3 Quantum 64-bit

#### Which operating system did you use (including version number)?
Windows 7 Enterprise

#### Did you log in to CS50 IDE using the same GitHub account you used to create this issue?
Yes.

**Comment by kzidane** [comment]
Do you actually have a server running in your workspace on port 8080?


Kareem

**Comment by sgilbert-student** [comment]
I did not. I thought that the purpose of the menu was to start the Web server (instead of apache50 like we did in the previous version of CS 50). I'll close the issue.
