### ISSUE TITLE
Something went wrong - error

### ISSUE THREAD

**Issue by rajeevreddyms5** [cs50/v4-issues#21]
#### What symptom did you see (attaching screenshots as necessary)?

Something went wrong error

#### When date and time (UTC) did the problem happen?
1:35 pm
Saturday, 18 May 2019
Coordinated Universal Time (UTC)

#### What steps did you follow to reproduce the problem?
1. step 1
1. step 2
1. step 3

#### Which web browser did you use (including version number)?
safari

#### Which operating system did you use (including version number)?
macOS 

#### Did you log in to CS50 IDE using the same GitHub account you used to create this issue?
yes
<img width="1280" alt="Screenshot 2019-05-18 at 7 09 16 PM" src="https://user-images.githubusercontent.com/6987056/57970570-5e940d00-79a0-11e9-8572-e73ac306b7ad.png">

**Comment by iUtsavB** [comment]
same happening with me too :/

**Comment by rajeevreddyms5** [comment]
Now it is just displaying white blank page

**Comment by kzidane** [comment]
Please try using the latest version of Chrome or Firefox for now!
