### ISSUE TITLE
CS50 IDE Won't open

### ISSUE THREAD

**Issue by TrueFallDino** [cs50/v4-issues#22]
#### What steps did you follow to reproduce the problem?
1. open https://ide.cs50.io
2. login into my github account.
3. wait 2 minutes.

**Comment by kzidane** [comment]
Does the issue get resolved if you simply reload the page?

**Comment by TrueFallDino** [comment]
I've tried cleaning my browser and reloading the page, but it didn't help.

**Comment by TrueFallDino** [comment]
It finally loaded.
