### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by NeyBots** [cs50/v4-issues#23]
#### What steps did you follow to reproduce the problem?
1. Showing me this error
-
CS50 IDE beta
Something went wrong
Failed to start your workspace. Please take a moment to report the problem. Let sysadmins@cs50.harvard.edu know if the problem persists!
-

**Comment by kzidane** [comment]
Hi @NeyBots, do you still have the same issue after reloading the page?

**Comment by NeyBots** [comment]
yes worked but i try again to install quick.db with npm install quick.db and again give the error https://cdn.discordapp.com/attachments/553310632473001984/585110961858543646/unknown.png

**Comment by kzidane** [comment]
Afraid I don't see any IDE-specific issues here, @NeyBots!
