### ISSUE TITLE
just a white page on firefox 67.0.1 (runs on chrome)

### ISSUE THREAD

**Issue by erika6** [cs50/v4-issues#24]
#### What symptom did you see (attaching screenshots as necessary)?
at first the ide seems to be loading fine, but then ends up showing a blank page.

#### When date and time (UTC) did the problem happen?
around sat 8 jun 2019, 07:09:22
and since a couple days before.

#### What steps did you follow to reproduce the problem?
logging in

#### Which web browser did you use (including version number)?
firefox 67.0.1

#### Which operating system did you use (including version number)?
ubuntu 18.04.2 lts

#### Did you log in to CS50 IDE using the same GitHub account you used to create this issue?
well, yes! ^^

**Comment by kzidane** [comment]
Are you using any adblockers or have third-party cookies disabled in your browser by chance?

**Comment by rajeevreddyms5** [comment]
The same issue is happening with safari in Macbook

**Comment by erika6** [comment]
@kzidane, hello!
sure! i have uMatrix and noScript blockers, but i had already tried deactivating them.
----> 'twas the browser cookie parameters!
the problem persisted when i allowed 3rd party cookies, though.
it only ran when i lowered the permissions to 'cookies from non visited websites'... and i'm very not pleased about that...!! :///
but thanks for your help, now i know what it was ^^

**Comment by kzidane** [comment]
@rajeevreddyms5 that's a known issue with Safari that we're looking into. In the meantime please use the latest version of Google Chrome or Firefox.

**Comment by jakin6** [comment]
Also now I am having the same problem

**Comment by kzidane** [comment]
@jakin6 which browser are you using? Do you have any adblockers or other browser extensions installed?

**Comment by jakin6** [comment]
I use firefox
