### ISSUE TITLE
Workspace does not load on Google Chrome

### ISSUE THREAD

**Issue by SNathJr** [cs50/v4-issues#26]
#### What symptom did you see (attaching screenshots as necessary)?

I received error `signin.aws.amazon.com refused to connect.`

![image](https://user-images.githubusercontent.com/20180524/59496977-2f45c280-8eb0-11e9-89ce-f798a488bce0.png)

**Developer Console Error 1:**

`Refused to display 'https://signin.aws.amazon.com/federation?Action=login&Issuer=ide.cs50.io&Destination=https://us-west-2.console.aws.amazon.com/cloud9/ide/4dbxx2e5e3a64xxf87f3e1axxxx59x20&SigninToken=xxxxxxx' in a frame because it set 'X-Frame-Options' to 'deny'.`

**Developer Console Error 2:**

`Failed to load resource: the server responded with a status of 400 (Bad Request)`

#### When date and time (UTC) did the problem happen?

Since last 4 days

8:42 am
Friday, 14 June 2019
Coordinated Universal Time (UTC)

#### What steps did you follow to reproduce the problem?
1. step 1

go to https://ide.cs50.io

2. step 2

Sign in through github

1. step 3

#### Which web browser did you use (including version number)?

Google Chrome (latest)

#### Which operating system did you use (including version number)?

Windows 10

#### Did you log in to CS50 IDE using the same GitHub account you used to create this issue?

Yes

**Comment by SNathJr** [comment]
@kzidane 

I am not sure what happened, but it seemed to have been fixed. But now there are a lot of new errors in the console:

**Error 1:**
```
globalnav-9247c6296ff6e871afcbc23e2c4fd5d04a27f68f.gz.js:40 Uncaught DOMException: Blocked a frame with origin "https://us-west-2.console.aws.amazon.com" from accessing a cross-origin frame.
    at Object.initialize (https://d3rrzw75sdtfe5.cloudfront.net/js/menu-2kjdfskljflksdfjk/globalnav-9247c6296ff6e871afcbc23e2c4fd5d04a27f68f.gz.js:40:90952)
    at https://d3rrzw75sdtfe5.cloudfront.net/js/menu-2kjdfskljflksdfjk/globalnav-9247c6296ff6e871afcbc23e2c4fd5d04a27f68f.gz.js:40:109667
```

**Error 2:**
```
Uncaught DOMException: Blocked a frame with origin "https://us-west-2.console.aws.amazon.com" from accessing a cross-origin frame.
    at https://d3rrzw75sdtfe5.cloudfront.net/js/mezz-35gbnwov975sjdhcbsf/mezz-39ae1ec10a35e98cd5be3b5d70b70ed283129b6c.gz.js:1:442
    at https://d3rrzw75sdtfe5.cloudfront.net/js/mezz-35gbnwov975sjdhcbsf/mezz-39ae1ec10a35e98cd5be3b5d70b70ed283129b6c.gz.js:1:3469
```
**Error 3:**
```
environment-default.js:48745 ERROR Error: {"error":{"code":499,"message":"VFS connection does not exist"}}
    at XMLHttpRequest.xhr.onload (https://d3gac9ws0uwh3y.cloudfront.net/c9-526050bf6069-ide/build/configs/ide/@aws/cloud9/configs/ide/environment-default.js:49186:73)
log @ environment-default.js:48745
```
**Error 4:**
```
environment-default.js:48365 9cIavwlerlgkl28B deleted Error: {"error":{"code":499,"message":"VFS connection does not exist"}}
    at XMLHttpRequest.xhr.onload (environment-default.js:49186)
(anonymous) @ environment-default.js:48365
```
**Error 5:**
```
worker.js:11521 TernError: No type found at the given position.
    at ternError (https://d3gac9ws0uwh3y.cloudfront.net/c9-526050bf6069-ide/modules/@c9/ide/plugins/c9.ide.language.core/worker.js:8289:9)
    at findExprType (https://d3gac9ws0uwh3y.cloudfront.net/c9-526050bf6069-ide/modules/@c9/ide/plugins/c9.ide.language.core/worker.js:8422:16)
    at Object.findTypeAt [as run] (https://d3gac9ws0uwh3y.cloudfront.net/c9-526050bf6069-ide/modules/@c9/ide/plugins/c9.ide.language.core/worker.js:8430:45)
    at run (https://d3gac9ws0uwh3y.cloudfront.net/c9-526050bf6069-ide/modules/@c9/ide/plugins/c9.ide.language.core/worker.js:8245:22)
    at Object.exports.withContext (https://d3gac9ws0uwh3y.cloudfront.net/c9-526050bf6069-ide/modules/@c9/ide/plugins/c9.ide.language.core/worker.js:7895:12)
    at https://d3gac9ws0uwh3y.cloudfront.net/c9-526050bf6069-ide/modules/@c9/ide/plugins/c9.ide.language.core/worker.js:8251:29
    at analyzeAll (https://d3gac9ws0uwh3y.cloudfront.net/c9-526050bf6069-ide/modules/@c9/ide/plugins/c9.ide.language.core/worker.js:8282:6)
    at doRequest (https://d3gac9ws0uwh3y.cloudfront.net/c9-526050bf6069-ide/modules/@c9/ide/plugins/c9.ide.language.core/worker.js:8243:57)
    at exports.Server.request (https://d3gac9ws0uwh3y.cloudfront.net/c9-526050bf6069-ide/modules/@c9/ide/plugins/c9.ide.language.core/worker.js:8526:1)
    at BaseHandler.handler.$request (https://d3gac9ws0uwh3y.cloudfront.net/c9-526050bf6069-ide/modules/@c9/ide/plugins/c9.ide.language.core/worker.js:11551:16)
(anonymous) @ worker.js:11521
```
**Error 6:**
```
worker.js:12106 8866: 145: Error: Collab server failed to provide document contents in time
    at Timeout.<anonymous> (jsonalyzer_server:65:28)
    at tryOnTimeout (timers.js:228:11)
    at Timer.listOnTimeout (timers.js:202:5)
```

**Comment by kzidane** [comment]
@SNathJr do you happen to have adblockers installed or third-party cookies disabled?

**Comment by SNathJr** [comment]
@kzidane 
No I do not have third party cookies disabled

![image](https://user-images.githubusercontent.com/20180524/59718632-31a17700-9238-11e9-908b-14863a4b4f4c.png)

I also have disabled all browser extensions

![image](https://user-images.githubusercontent.com/20180524/59718673-44b44700-9238-11e9-8a8d-5e1d824e8819.png)

**Comment by kzidane** [comment]
@SNathJr do you have another AWS Console session by chance?

**Comment by SNathJr** [comment]
@kzidane No, I do not have another console, however I sometimes use an offline version of CS50 ide running inside WSL (Windows Subsystem for Linux)

**Comment by kzidane** [comment]
@SNathJr if you try the latest version of Firefox, do you get the same issue?

**Comment by SNathJr** [comment]
@kzidane 
 On the latest version of Firefox there are a few XML errors:

```
XML Parsing Error: no root element found
Location: https://vfs.cloud9.us-west-2.amazonaws.com/vfs/d9xxxxxx26xxxxxx810xxxxxxxx16xx/environment/_/_/tab0
Line Number 1, Column 1:
```

```
XML Parsing Error: no root element found
Location: https://vfs.cloud9.us-west-2.amazonaws.com/vfs/d9exxxxx26xxxxxxxxxxa4xxxxx16xx/environment/flask-social-network-master/Payments.py
Line Number 1, Column 1:
```

Also there are errors like that of Chrome:

```
9cs8swhH083rU23j deleted Error: "{"error":{"code":499,"message":"VFS connection does not exist"}}"
    ide aws/cloud9/configs/ide/environment-default.js:49185

    destroyVfsCache https://d3gac9ws0uwh3y.cloudfront.net/c9-9a66299fe1cd-ide/build/configs/ide/@aws/cloud9/configs/ide/environment-default.js:48364
    done https://d3gac9ws0uwh3y.cloudfront.net/c9-9a66299fe1cd-ide/build/configs/ide/@aws/cloud9/configs/ide/environment-default.js:49155
    onload https://d3gac9ws0uwh3y.cloudfront.net/c9-9a66299fe1cd-ide/build/configs/ide/@aws/cloud9/configs/ide/environment-default.js:49186
```

```
ERROR request/xhr.onload@https://d3gac9ws0uwh3y.cloudfront.net/c9-9a66299fe1cd-ide/build/configs/ide/@aws/cloud9/configs/ide/environment-default.js:49185:73

    log https://d3gac9ws0uwh3y.cloudfront.net/c9-9a66299fe1cd-ide/build/configs/ide/@aws/cloud9/configs/ide/environment-default.js:48744
    onload https://d3gac9ws0uwh3y.cloudfront.net/c9-9a66299fe1cd-ide/build/configs/ide/@aws/cloud9/configs/ide/environment-default.js:49186
```

```
SecurityError: Permission denied to access property "pathname" on cross-origin object
    <anonymous> https://d3rrzw75sdtfe5.cloudfront.net/js/mezz-35gbnwov975sjdhcbsf/mezz-39ae1ec10a35e98cd5be3b5d70b70ed283129b6c.gz.js:1
    <anonymous> https://d3rrzw75sdtfe5.cloudfront.net/js/mezz-35gbnwov975sjdhcbsf/mezz-39ae1ec10a35e98cd5be3b5d70b70ed283129b6c.gz.js:1
```

```
SecurityError: Permission denied to access property "protocol" on cross-origin object
    initialize https://d3rrzw75sdtfe5.cloudfront.net/js/menu-2kjdfskljflksdfjk/globalnav-0578c7f79093b0f6f04b10a335f82fcd24da42d0.gz.js:40
    <anonymous> https://d3rrzw75sdtfe5.cloudfront.net/js/menu-2kjdfskljflksdfjk/globalnav-0578c7f79093b0f6f04b10a335f82fcd24da42d0.gz.js:40
```

**Comment by kzidane** [comment]
@SNathJr this sounds like the doing of some sort of adblocker. Are you absolutely sure you don't have any adblockers enabled on this machine? Can you try from a different machine by chance?

**Comment by SNathJr** [comment]
@kzidane I am absolutely sure that there are no ad blockers on my machine (other than default windows firewall of course). Also, I am getting similar errors on a mac book (chrome) and a linux (firefox). Then I thought may be my ISP is the issue, so I tried with a different internet connection, but still the similar errors appeared.

**Comment by SNathJr** [comment]
@kzidane This issue appeared again in my CS50 IDE. 
![image](https://user-images.githubusercontent.com/20180524/60242403-42ef2100-98d3-11e9-9f7c-008a851e5fa2.png)

**Comment by SNathJr** [comment]
@kzidane I reloaded the page, with only the base URL (https://ide.cs50.io) and this happened:
![image](https://user-images.githubusercontent.com/20180524/60242694-e17b8200-98d3-11e9-9af0-89db5e2f403e.png)

**Comment by SNathJr** [comment]
@kzidane I deleted all my browser history and cookies and tried again. And this time it took me to my workspace smoothly. 

I was just thinking, is it possible that all these issues are coming up because of old session cookies (as the next time you login to your ide your session and instance would both change, causing some conflict)? If this is the cause, how about deleting old cookies and creating new ones, every time a user logs in (given the old session is expired).

**Comment by kzidane** [comment]
@SNathJr out of curiosity, when you reload do you press Ctrl + R or hit the reload button?

**Comment by SNathJr** [comment]
@kzidane I usually press the `F5` key to reload the page.

**Comment by mahnoorsheikh16** [comment]
did you solve this problem? I am facing the same issue

**Comment by kzidane** [comment]
This should be fixed.
