### ISSUE TITLE
CS50 IDE Not Opening

### ISSUE THREAD

**Issue by Adam-JBeck** [cs50/v4-issues#27]
#### What symptom did you see (attaching screenshots as necessary)?
I am getting this message when I try to sign in:
![image](https://user-images.githubusercontent.com/14208181/59570842-10336600-9053-11e9-9f00-6e416038a55a.png)

#### When date and time (UTC) did the problem happen?
4:00pm-4:20pm pst
#### What steps did you follow to reproduce the problem?
1. Tried to log into my IDE and it would not let me in.

#### Which web browser did you use (including version number)?
Chrome 75.0.3770.90 (Official Build) (64-bit)
#### Which operating system did you use (including version number)?
Windows 10
#### Did you log in to CS50 IDE using the same GitHub account you used to create this issue?
Yes

**Comment by kzidane** [comment]
If you reload the page, do you see the same problem?

**Comment by KMDJI1** [comment]
I am having a similar problem. 

When I log into the CS50 IDE using the GitHub, it directs me here
https://us-west-2.console.aws.amazon.com/cloud9/ide/0100baae81f4421194f41cf9a4019b50?#
where I am not able to compile the examples the professor uses during classes

**Comment by kzidane** [comment]
@KMDJI1 can you elaborate more please?

**Comment by KMDJI1** [comment]
I am unable to compile a program in the ide environnement using my CS50 account. Below is the output I get when I try to compile a code. My filename=pog.
Thanks
~/ $ make progmake: Nothing to be done for 'prog'.~/ $ ./progbash: ./prog: Permission denied

    Le vendredi 24 avril 2020 à 16:14:04 UTC−4, Kareem Zidane <notifications@github.com> a écrit :  
 
 


@KMDJI1 can you elaborate more please?

**Comment by kzidane** [comment]
@KMDJI1 this appears to be unrelated to the issue and doesn't sound like an IDE issue. It sounds like you need to make sure you're in the right folder and running the right `make` command for this to work. Best to ask questions like these on CS50's online communities. You can see a list of these communities at https://cs50.harvard.edu/x/2020/.
