### ISSUE TITLE
Github Auth Failed

### ISSUE THREAD

**Issue by 09jlardinois** [cs50/v4-issues#3]
#### What symptom did you see (attaching screenshots as necessary)?
GitHub password **authentication always fails, even with correct passwords** (_many tests done to ensure correct, verbatim, or otherwise impossible to type incorrectly_).

Screenshot on standby if needed.

My thought: I have a sneaking feeling it's a 2FA problem. Instead of prompting for 2F it's just immediately attempting the auth which GitHub then immediately rejects without 2FA. 

#### When date and time (UTC) did the problem happen?
10:32PM | 22:32 UTC

#### What steps did you follow to reproduce the problem?
1. git clone [repository]
2. enter username 
3. _enter password_ :: _*failed*_ 
A. ____attempted with new password, simple password, copy / paste in all cases, manual typing in all cases.

#### Which web browser did you use (including version number)?
**Chrome** current, stable.
Version **71.0.3578.98** (Official Build) (64-bit)

#### Which operating system did you use (including version number)?
Windows **10 64 Pro**
Version **1809**, Build **17763.253**

#### Did you log in to CS50 IDE using the same GitHub account you used to create this issue?
**Yes**. I hope that helps debugging :)

**Comment by kzidane** [comment]
Afraid this doesn't seem like a CS50 IDE issue! That said, if you're using 2FA, I believe you will need to use a GitHub personal access token in place of the password when doing HTTP auth. You should be able to generate one at https://github.com/settings/tokens.
