### ISSUE TITLE
Something Went Wrong when Signing In

### ISSUE THREAD

**Issue by tj-mc** [cs50/v4-issues#33]
#### What symptom did you see (attaching screenshots as necessary)?
'Something Went Wrong'
Failed to start your workspace

#### When date and time (UTC) did the problem happen?
10:59:01 UTC
Sunday, June 23, 2019

#### What steps did you follow to reproduce the problem?
1. Visited ide.cs50.io
2. Clicked sign in with github

#### Which web browser did you use (including version number)?
Chrome Version 75.0.3770.100

#### Which operating system did you use (including version number)?
MacOS 10.14.5 (18F132)

#### Did you log in to CS50 IDE using the same GitHub account you used to create this issue?
Yes

**Comment by tj-mc** [comment]
When I attempted to login with chrome in incognito mode, I gained access to an account that was not mine. I have also reported this issue to the sysadmins@cs50 address.

**Comment by kzidane** [comment]
Thanks for reporting the issue, @tommcintosh99! This should be fixed now.
