### ISSUE TITLE
 Something went wrong. Failed to start your workspace.

### ISSUE THREAD

**Issue by tomstrand** [cs50/v4-issues#35]
#### What symptom did you see (attaching screenshots as necessary)?
 Something went wrong
 Failed to start your workspace.
#### When date and time (UTC) did the problem happen?
 Sunday, June 23, 2019 
 12:27 PM
#### What steps did you follow to reproduce the problem?
1. step 1 went to https://ide.cs50.io/
1. step 2 pressed sign in using github

#### Which web browser did you use (including version number)?
Firefox 67.0.1 (64-bit) 
Google Chrome Version 75.0.3770.100 (Official Build) (64-bit)
#### Which operating system did you use (including version number)?
MacOS Mojave version 10.14.5 (18F132)
#### Did you log in to CS50 IDE using the same GitHub account you used to create this issue?
yes

**Comment by hetanthakkar** [comment]
same issue . please  resolve it asap as i am having deadine for my assignment which i coded in cs50 ide

**Comment by kzidane** [comment]
@tomstrand @hetanthakkar1 if you reload the page, do you still see the same issue?

**Comment by tomstrand** [comment]
@kzidane  Yes, have tried to reload on both browsers. Also tried to empty cache and hard reload. Same issue.

**Comment by kzidane** [comment]
@tomstrand can you try one more time now please?

**Comment by tomstrand** [comment]
@kzidane Now it works, on both Chrome and Firefox. Thank you!
