### ISSUE TITLE
Failed to open Workspace

### ISSUE THREAD

**Issue by loh1468** [cs50/v4-issues#36]
#### What symptom did you see (attaching screenshots as necessary)?
![Screenshot_2019-06-23 CS50 IDE](https://user-images.githubusercontent.com/48852479/59984180-565d6c00-95f5-11e9-81d9-beda5a17064a.png)

#### When date and time (UTC) did the problem happen?
6/23/19 9:00 AM UTC and 12:20 AM UTC
#### What steps did you follow to reproduce the problem?
1. Loaded the IDE from the PSET page 
1. Pressed the "login via github" as usual (had no problem last night or this past week)
1. Refreshed multiple times

-also whitelisted site on adblocker.
-tried incognito mode
-also enabled cookies

#### Which web browser did you use (including version number)?
Firefox Quantum 67.0.04
#### Which operating system did you use (including version number)?
Windows 10 Home 10.0.17134 Build  17134
#### Did you log in to CS50 IDE using the same GitHub account you used to create this issue?  
Yes

**Comment by kzidane** [comment]
Does the same issue happen if you reload the page, @loh1468?

**Comment by loh1468** [comment]
Yes i just tried to reload and the same issue is happening.  I've tried it on both my desktop and laptop multiple times today

**Comment by loh1468** [comment]
It is working now. I think it was just the IDE migrating that caused problems. All is well now thank you
