### ISSUE TITLE
Issue with login with Github Account

### ISSUE THREAD

**Issue by ahmadibraali** [cs50/v4-issues#37]
#### What symptom did you see (attaching screenshots as necessary)?
'Something Went Wrong'
Failed to start your workspace
#### When date and time (UTC) did the problem happen?
10:59:01 UTC
Sunday, June 23, 2019
#### What steps did you follow to reproduce the problem?
1. Visited ide.cs50.io
2. Clicked sign in with github

#### Which web browser did you use (including version number)?
Chrome Version 75.0.3770.100 (Official Build) (64-bit)
#### Which operating system did you use (including version number)?
Windows 10  
#### Did you log in to CS50 IDE using the same GitHub account you used to create this issue?
Yes 
![image](https://user-images.githubusercontent.com/26085108/59984317-10220000-9629-11e9-99e8-c816eb98078f.png)

**Comment by kzidane** [comment]
Try reloading now, @Ahmedibr2020?

**Comment by ahmadibraali** [comment]
> Try reloading now, @Ahmedibr2020?
@kzidane 
Seems to be working again now , Thanx a lot 💯
