### ISSUE TITLE
cs50 ide not loading

### ISSUE THREAD

**Issue by KillingJoke42** [cs50/v4-issues#39]
#### What symptom did you see (attaching screenshots as necessary)?
cs50 ide not moving past "preparing your environment"

![cs50ide](https://user-images.githubusercontent.com/49367372/59997554-02956600-967b-11e9-8323-ec8325f66525.png)

#### When date and time (UTC) did the problem happen?
6.55 am Monday UTC
#### What steps did you follow to reproduce the problem?
1. step 1 visit ide.cs50.io
1. step 2 sign in with GitHub
1. step 3 wait 2-3minutes
1. step 4 tried reloading to no avail
1. step 5 tried another browser to no avail
1. step 6 tried clearing browser cache to no avail

#### Which web browser did you use (including version number)?
Google Chrome Version 75.0.3770.100 (Official Build) (64-bit), Microsoft Edge, Google Chrome Mobile
#### Which operating system did you use (including version number)?
Windows 10 version 1809 (OS build 17763.557)
#### Did you log in to CS50 IDE using the same GitHub account you used to create this issue?
Yes

**Comment by kzidane** [comment]
Could you try reloading the page now please?

**Comment by KillingJoke42** [comment]
I tried doing that.....it's still stuck on "preparing your environment"

**Comment by kzidane** [comment]
@KillingJoke42 what if you try now?

**Comment by KillingJoke42** [comment]
It seems to work......thanks a lot!

**Comment by kzidane** [comment]
Thanks for confirming! Please let us know if you run into other issues.
