### ISSUE TITLE
Please fix the buggy console drag area (and other requests)

### ISSUE THREAD

**Issue by SNathJr** [cs50/v4-issues#41]
#### What symptom did you see (attaching screenshots as necessary)?

> Problem 1: When I open the IDE the console area is hidden below the task bar

![image](https://user-images.githubusercontent.com/20180524/61584195-299f6480-ab61-11e9-81f7-8f2daa1957e9.png)

> Problem 2: The dragging area that should be there is missing!!!

![image](https://user-images.githubusercontent.com/20180524/61584215-8a2ea180-ab61-11e9-9fd2-a03001bd3a92.png)

> Request 1: Please bring back the old CS50 IDE landing page, it looked way cooler :)

> Request 2: Please, Please, Please Increase the IDE time out from 30 minutes to at least an hour, many of the times IDE times out while watching the video lecture

#### When date and time (UTC) did the problem happen?

9:18 pm
Saturday, 20 July 2019
Coordinated Universal Time (UTC)

#### What steps did you follow to reproduce the problem?

Just open the IDE in the browser

#### Which web browser did you use (including version number)?

Chrome Latest

#### Which operating system did you use (including version number)?

Windows 10

#### Did you log in to CS50 IDE using the same GitHub account you used to create this issue?
Yes

#### Possible solution to the above mentioned bug

Though it fixes the dragging area, but it is an inconvenience for doing every time you open the IDE. You just need to maximize the console and then minimize it again, and the dragging area re-appears.

![image](https://user-images.githubusercontent.com/20180524/61584263-5bfd9180-ab62-11e9-8aa0-5a946a409843.png)

![image](https://user-images.githubusercontent.com/20180524/61584264-6455cc80-ab62-11e9-8e44-f1727fa4478d.png)

**Comment by SNathJr** [comment]
@kzidane Thank you, this issue is fixed now!

**Comment by SNathJr** [comment]
@kzidane So, this issue started happening again

**Comment by kzidane** [comment]
Does it happen if you click CS50 IDE > Reset Settings?


Kareem

**Comment by SNathJr** [comment]
@kzidane After resetting the settings, it seemed to have fixed the problem. Thank you!
