### ISSUE TITLE
Does SSH work with Github?

### ISSUE THREAD

**Issue by sgilbert-student** [cs50/v4-issues#42]
#### What symptom did you see (attaching screenshots as necessary)?
I am setting up the IDE for my students for the Fall. With the old version, I had them generate SSH keys and connect to their Github accounts. That allowed me to script their homework assignments to push everytime they compiled. With the new IDE (instead of the Account dialog), I don't seem to be able to generate separate keys to connect to Github.  I don't know if this is related to the fact that the new IDE uses Github for authentication.

I have both generated a new key pair and used the ..ssh/authorized_keys that already seem to exist and in both cases I was not able to connect to github.

#### When date and time (UTC) did the problem happen?
Fri Jul 26 00:56:50 UTC 2019

#### What steps did you follow to reproduce the problem?
1. Went to github-settings and added a new SSH key using authorized_keys
2. Tried to connect with ssh -T git@github.com (per github docs) Times out
3.  Generated a new key using ssh_keygen, added it to the agent and to github times out as well

#### Which web browser did you use (including version number)?
Chrome (latest)
#### Which operating system did you use (including version number)?
Windows 7
#### Did you log in to CS50 IDE using the same GitHub account you used to create this issue?
Yes

**Comment by sgilbert-student** [comment]
I should mention that the https works just fine.

**Comment by kzidane** [comment]
I'm afraid outbound traffic on port 22 are blocked on the new IDE for security reasons. GitHub however allows you to make an SSH connection to port 443 instead which is open on the IDE. See https://help.github.com/en/articles/using-ssh-over-the-https-port for more information. Let us know if you need further help!
