### ISSUE TITLE
Environment ran out of quota

### ISSUE THREAD

**Issue by SNathJr** [cs50/v4-issues#43]
#### What symptom did you see (attaching screenshots as necessary)?

My CS50 IDE ran out of quota.

![image](https://user-images.githubusercontent.com/20180524/62834711-ecb12400-bc6d-11e9-89b3-2c5b5fe28e32.png)

The issue seem to be low storage allocation to /home/ubuntu volume.

![image](https://user-images.githubusercontent.com/20180524/62834732-1702e180-bc6e-11e9-9a2d-e07fbcc3e97c.png)

#### When date and time (UTC) did the problem happen?

1:57 pm
Sunday, 11 August 2019
Coordinated Universal Time (UTC)

#### What steps did you follow to reproduce the problem?

NOT APPLICABLE

#### Which web browser did you use (including version number)?

Chrome Latest

#### Which operating system did you use (including version number)?

Windows 10 Pro 1903

#### Did you log in to CS50 IDE using the same GitHub account you used to create this issue?

Yes

**Comment by SNathJr** [comment]
@kzidane Can we have a little bit more than 1GiB in home directory, please?

**Comment by dlloyd09** [comment]
Sorry, can't increase the limit on our tier of accounts!
