### ISSUE TITLE
Creating virtual environment with python venv module gives error

### ISSUE THREAD

**Issue by SNathJr** [cs50/v4-issues#46]
#### What symptom did you see (attaching screenshots as necessary)?

```Error: Command '['/home/ubuntu/venv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.```

#### When date and time (UTC) did the problem happen?

7:01 pm
Saturday, 21 September 2019
Coordinated Universal Time (UTC)

#### What steps did you follow to reproduce the problem?
```python -m venv venv```

#### Which web browser did you use (including version number)?

Chrome latest

#### Which operating system did you use (including version number)?

Windows 10 latest

#### Did you log in to CS50 IDE using the same GitHub account you used to create this issue?
Yes

#### More details

though [this github issue](https://github.com/ContinuumIO/anaconda-issues/issues/6917) gives a possible solution, but I would like to know if there is any cleaner method. Or if I broke my CS50 IDE!?

**Comment by SNathJr** [comment]
This issue seems to have caused by lack of space on the IDE. Making space empty seems to have fixed the issue. Thanks anyways. I would really love to see just a little bit extra space on the IDE.

**Comment by dannielshalev** [comment]
I have the same issue, there is a workaround?

**Comment by kzidane** [comment]
@dannielshalev if you're running out of space, you may run `du -h /home/ubuntu | sort -h` to figure out if there any files that are taking up disk space that you don't need and remove them.
