### ISSUE TITLE
Can't log in to submit

### ISSUE THREAD

**Issue by aegis301** [cs50/v4-issues#47]
#### What symptom did you see (attaching screenshots as necessary)?
When I try to log in with my GitHub Account to submit a pset in the CS50 Lab, I always get back: Invalid Username/Password. Even though I'm using the PW I use when i log into my GitHub account and it works without problems. I enrolled in the CS50 course and I have a registered Pset0 in submit.cs50.io and a score for Pset0 in me.cs50...so I'm guessing it has nothing to do with my subscription.
#### When date and time (UTC) did the problem happen?
Since a few days continuing
#### What steps did you follow to reproduce the problem?
Used the suggested command in the terminal window

#### Which web browser did you use (including version number)?
Firefox 70.0.1
#### Which operating system did you use (including version number)?
Windows 10 Home V10.0.18362
#### Did you log in to CS50 IDE using the same GitHub account you used to create this issue?
Yes

**Comment by kzidane** [comment]
This doesn't seem like an IDE issue. Please email sysadmin@cs50.harvard.edu!
