### ISSUE TITLE
Go to Anything (Ctrl-P) pane just started appearing.

### ISSUE THREAD

**Issue by sgilbert-student** [cs50/v4-issues#48]
#### What symptom did you see (attaching screenshots as necessary)?
In the file tree, a Go to Anything pane just started appearing at the top, obscuring the root folder and just barely showing the file-tree gear widget.

![ide](https://user-images.githubusercontent.com/36554337/73891665-93dfd400-4829-11ea-905b-48600e187dad.png)

#### When date and time (UTC) did the problem happen?
Noticed it this morning (Feb 5, 2020)

#### What steps did you follow to reproduce the problem?
1. Opened the ide in Firefox
2. Opened a different account in Chrome
3. Checked my student's accounts as well
#### Which web browser did you use (including version number)?
Latest chrome, firefox; appears in Edge as well, although I don't use that

#### Which operating system did you use (including version number)?
Windows 10 (latest)
#### Did you log in to CS50 IDE using the same GitHub account you used to create this issue?
Yes, as well as several others.

**Comment by kzidane** [comment]
Thanks for reporting this! We'll look into it asap.

**Comment by kzidane** [comment]
This should be now fixed.
