### ISSUE TITLE
Unable to delete a file

### ISSUE THREAD

**Issue by kzidane** [cs50/v4-issues#49]
I made a directory called readability and opened a file readbility.c in it. I accidentally deleted the file. Since I had not coded much, I just decided to open a new file of the same name. However, when I type in the command 'open readability.c,' the same deleted file opens up but it does not show up in the file tree. And I am unable to compile it because the file does not actually exist in the readability directory. Is there a way I can start the pset2 Readability afresh? I tried by deleting the directory. But when I made the directory once again and tried to open the readability.c file in it, the same deleted file is opened 
![20200428_162435](https://user-images.githubusercontent.com/64054535/80479808-39a86800-896d-11ea-8a95-10230f97dec0.jpg)
up.

_Originally posted by @Abhigya3159 in https://github.com/cs50/ide-issues/issues/18#issuecomment-620538247_

**Comment by kzidane** [comment]
@Abhigya3159 did you delete the file while it's open? If so, try closing the file before deleting it.

**Comment by Abhigya3159** [comment]
I closed the file and then tried deleting it. I used the rm command to
delete the file but it does not work because the file does not exist in the
file tree.

**Comment by kzidane** [comment]
To create a new fill the, click the + icon and choose **New File** or right-click on the folder and choose the same option.

**Comment by Abhigya3159** [comment]
It worked. Thank you.
