### ISSUE TITLE
Autocomplete Case Sensitive

### ISSUE THREAD

**Issue by 09jlardinois** [cs50/v4-issues#5]
#### What symptom did you see (attaching screenshots as necessary)?
Terminal auto complete is case sensitive. I don't remember that ever being... the case. Pun intended. 

I'm not sure if this is really a bug or if it's always this way, but I have the muscle memory of it not being there, so I thought I'd report it. 

#### When date and time (UTC) did the problem happen?
Feb. 6, 2019
11:59PM UTC | 23:59PM

#### What steps did you follow to reproduce the problem?
1. Uploaded a file called Gameplay
1. Attempted various commands with tab to complete (style50, rm, cp)
1. Attempted to tab-complete "game-". 

#### Which web browser did you use (including version number)?
I'm not sure. I use Chrome, but as soon as I opened About Chrome to see the version, it started updating! So I really don't know what version was previously installed. 

#### Which operating system did you use (including version number)?
Win 10 x64 Pro
Version	10.0.17763 Build 17763

#### Did you log in to CS50 IDE using the same GitHub account you used to create this issue?
Yes.

**Comment by kzidane** [comment]
Hi @09jlardinois,

Thanks for trying CS50 IDE (beta)! By default, bash (the default command-line interpreter in the IDE) doesn't ignore case when auto-completing, but you should be able to enable that option by following the instructions here: https://askubuntu.com/a/87066/207935. If you want these changes to persist, you can add these lines to the end of your `~/.bashrc` file. `~/.bashrc` may not exist or may be hidden by default. One way to open it is by running  `open ~/.bashrc` in terminal tab.
