### ISSUE TITLE
After logging in to CS50 IDE, it wants me to download AWS Cloud9 Installer

### ISSUE THREAD

**Issue by RAnne127** [cs50/v4-issues#50]
#### What symptom did you see (attaching screenshots as necessary)?
I was just compiling my all my folders currently at home/ubuntu to a folder. Suddenly this shows up.
![image](https://user-images.githubusercontent.com/65267541/86324494-371a0580-bc71-11ea-8770-2333a3d825e8.png)
![image](https://user-images.githubusercontent.com/65267541/86324557-48631200-bc71-11ea-9dea-058a3f4afff6.png)
![image](https://user-images.githubusercontent.com/65267541/86324600-616bc300-bc71-11ea-8b81-882a20c92e27.png)

But it doesn't install smoothly; both online and manually
![image](https://user-images.githubusercontent.com/65267541/86324940-e951cd00-bc71-11ea-821c-3a51e0dc06a7.png)

#### When date and time (UTC) did the problem happen?
6:38 AM

#### What steps did you follow to reproduce the problem?
1. I tried to install it again and again
1. 2 I used other browsers but the same thing happen.
1. 3 I even tried installing it manually.

#### Which operating system did you use (including version number)?
OS build18362.900
version 1903

#### Did you log in to CS50 IDE using the same GitHub account you used to create this issue?
Yes

**Comment by kzidane** [comment]
This should be fixed.

**Comment by ghost** [comment]
I'm having the same issue for over an hour now. I broke my IDE by deleting the c9 folder and now the installation of cloud9 always fails.
EDIT: It is now fixed.
