### ISSUE TITLE
IDE does not work on desktop

### ISSUE THREAD

**Issue by Nnanyere** [cs50/v4-issues#51]
#### What symptom did you see (attaching screenshots as necessary)?
![Capture](https://user-images.githubusercontent.com/64748532/93028564-af426700-f5e2-11ea-9fc5-dadeae82c185.JPG)
The IDE says that it is loading, but it keeps "loading" for minutes. Then, the error shown above pops up. This may be because 
the computer I am using is old (it has frequent Internet problems). While the IDE does work in other places, I do wish that I 
would have more time to complete the problem sets.
#### When date and time (UTC) did the problem happen?
The first time this happened is on May 3rd, 2020. I do not remember the exact time.
#### What steps did you follow to reproduce the problem?
1. I reloaded the site.
1. I used Email to try to solve the issue.
1. I tried other web browsers and even incognito.
#### Which web browser did you use (including version number)?
Google Chrome (I do not have the version number)
#### Which operating system did you use (including version number)?
Windows 10 (I think)
#### Did you log in to CS50 IDE using the same GitHub account you used to create this issue?
Yes.

**Comment by kzidane** [comment]
Do you happen to have any browser extensions installed? If so, can you try disabling them and try again? Can you also make sure you're running the most recent version of Chrome?

**Comment by Nnanyere** [comment]
After disabling all extensions and ensuring I was running the latest version of Chrome, the IDE still does not work.

**Comment by Nnanyere** [comment]
I have another question. If I am not able to complete the problem sets for the CS50 course, should I still watch the videos on edX associated with each week?

**Comment by kzidane** [comment]
I was able to load your IDE without a problem on my end per the screenshot which suggests the issue is somewhere on your end. Are you using a restricted machine or network? If you open Chrome's console by pressing Ctrl + Shift + J and visit ide.cs50.io, do you see any errors in the console when you get that error? Does the same issue happen on the latest version of Firefox?

![Screenshot from 2020-09-20 21-53-14](https://user-images.githubusercontent.com/7230211/93727989-d9b89500-fb8b-11ea-8868-c677bd2b33bc.png)

**Comment by Nnanyere** [comment]
This is the error message that I got first.

![image](https://user-images.githubusercontent.com/64748532/94348550-3c39e700-000b-11eb-8f01-e8ce872e0254.png)



After creating that screenshot, the error message changed.

![image](https://user-images.githubusercontent.com/64748532/94348566-570c5b80-000b-11eb-88a5-16da0a3d24a4.png)



I got 32 errors and 3 warnings after using the latest version of Firefox.

**Comment by Nnanyere** [comment]
I managed to open the IDE on other devices, but another problem arose while working on Plurality in Problem Set 3. When I tried using check50, I got a bunch of error messages telling me about lines in my code that didn't even exist since the numbers went above the amount of lines in my code. 
![image](https://user-images.githubusercontent.com/64748532/94477958-8f916e00-01a0-11eb-8fb7-748b4d2e531f.png)
The amount of lines in my program is 157. Is this a glitch or does this have something to do with actually running the program?

**Comment by kzidane** [comment]
@Nnanyere are you using a home network? Can you try using a different machine or network?

**Comment by Nnanyere** [comment]
@kzidane It turned out that one of the apps installed on my desktop was preventing the IDE from working, and the IDE worked just fine once the app was disabled. This isn't a problem anymore because the IDE now works with the 2021 version, even with the app enabled.
