### ISSUE TITLE
The Environment is running out of quota

### ISSUE THREAD

**Issue by Farah2030** [cs50/v4-issues#52]
#### What symptom did you see (attaching screenshots as necessary)?

![Capture](https://user-images.githubusercontent.com/68070288/96204134-82f76e80-0f31-11eb-8ea9-aeee7807a376.PNG)

![22](https://user-images.githubusercontent.com/68070288/96204143-8a1e7c80-0f31-11eb-8d42-6bbf90c0597b.PNG)

#### When date and time (UTC) did the problem happen?

Thursday 10/15/2020
10:01 AM EDT

#### What steps did you follow to reproduce the problem?

( every time I want to write in cs50 IDE )

#### Which web browser did you use (including version number)?

Google Chrome

#### Which operating system did you use (including version number)?

windows 10 version 2004

#### Did you log in to CS50 IDE using the same GitHub account you used to create this issue?

Yes

**Comment by kzidane** [comment]
Run the following command to see which files are eating up your disk space and (optionally back them up and) remove them:

```
du -h /home/ubuntu | sort -h
```

Please do not remove any files inside of the `~/.c9` folder.

**Comment by Farah2030** [comment]
Thanks for your reply.
I got this result , but I do not have a folder name HOME or file name "ubuntu" !

![as](https://user-images.githubusercontent.com/68070288/96801608-fbe54300-13d5-11eb-89b5-b3de60eff7aa.PNG)

**Comment by Farah2030** [comment]
Thanks for your reply.
I got this result

![e](https://user-images.githubusercontent.com/68070288/96801797-7910b800-13d6-11eb-81ab-9ec0aa7c62a1.PNG)

**Comment by kzidane** [comment]
Sorry, I edited the command on the previous comment. Can you try that instead?

**Comment by Farah2030** [comment]
thank you , it worked
