### ISSUE TITLE
CS50 IDE NOT OPENING

### ISSUE THREAD

**Issue by rzubairm** [cs50/v4-issues#54]
#### What symptom did you see (attaching screenshots as necessary)?
On clicking the page link "preparing your ide " appears and after that page goes blank.
#### When date and time (UTC) did the problem happen?
12:23 pm
#### What steps did you follow to reproduce the problem?
1. refreshing the page
1. changing the browser
1. opening in incognito mode

#### Which web browser did you use (including version number)?
Google Chrome
Version 87.0.4280.88 

#### Which operating system did you use (including version number)?
Windows 10
#### Did you log in to CS50 IDE using the same GitHub account you used to create this issue?
Yes

**Comment by kzidane** [comment]
Do you happen to have any adblockers or other browser extensions installed?

**Comment by jasonkhaings** [comment]
i cant open my IDE too

**Comment by rzubairm** [comment]
This issue still appears sometime. No i dont have any ad blocker.

**Comment by jasonkhaings** [comment]
No, i dont have any ad blockers either.

**Comment by kzidane** [comment]
@rzubairm @jasonkhaings if you open Chrome's console by pressing Ctrl + Shift + J, do you see any errors in the console when you visit ide.cs50.io and log in?

**Comment by KhathutsheloMakatu** [comment]
HI, this is how my console looks at the moment. And I want to complete my work

> @rzubairm @jasonkhaings if you open Chrome's console by pressing Ctrl + Shift + J, do you see any errors in the console when you visit ide.cs50.io and log in?

![Screenshot 2021-04-30 21 08 26](https://user-images.githubusercontent.com/71704227/116742929-6ff14b00-a9f8-11eb-94a5-3ef9051777ae.png)
