### ISSUE TITLE
CS50 IDE not working

### ISSUE THREAD

**Issue by irislinders** [cs50/v4-issues#55]
#### What symptom did you see (attaching screenshots as necessary)?
CS50 IDE Unable to load IDE 638d17b4ab4e492191fc60fda874cce8
in the Sourcecode it says bad gateway 502, Just to check i tryed to make a new account to check if I was able to log in with a diffrent account en that seems to work just fine. I did not try to log in since 2021, but it should be posible to use a acount made in 2020 right?

#### When date and time (UTC) did the problem happen?
10-1-2021
#### What steps did you follow to reproduce the problem?
1. step 1 try to open CS50 IDE
1. step 2 Loging in
1. step 3 delet al cookies and try to log in again

#### Which web browser did you use (including version number)?
google chrome, microsoft egde
#### Which operating system did you use (including version number)?
windows 10
#### Did you log in to CS50 IDE using the same GitHub account you used to create this issue?
yes

**Comment by kzidane** [comment]
Could you try again once more please?

**Comment by irislinders** [comment]
it worked!!
