### ISSUE TITLE
CS50 IDE not opening

### ISSUE THREAD

**Issue by shakteebiswal** [cs50/v4-issues#56]
#### What symptom did you see (attaching screenshots as necessary)?
CS50 IDE did not open

#### When date and time (UTC) did the problem happen?
6 Feb 2021 11.18 am UTC

#### What steps did you follow to reproduce the problem?
1. step 1 reloaded
1. step 2 opened tab in incognito
1. step 3 relogged in

#### Which web browser did you use (including version number)?
Google Chrome 88.0.4324.150
#### Which operating system did you use (including version number)?
Windows 7 Ultimate
#### Did you log in to CS50 IDE using the same GitHub account you used to create this issue?
Yes
![CS50-IDE](https://user-images.githubusercontent.com/77882155/107116675-e91a4f80-689a-11eb-8317-a71ea41273de.png)

**Comment by kzidane** [comment]
Can open that start menu and type `cmd` then open the cmd (or Command Prompt) app then run the following command:

```
nslookup ide-35c9caaf64194d0db68ea43e0d8562f5.ide.cs50.io
```

and paste the output here please?

Are you located in India and using Jio as your ISP by chance? If so, we have received many reports from users who are using the same ISP and have been having DNS issues. One way to get around this is to use different DNS (e.g., Google's) and try again. See https://developers.google.com/speed/public-dns/docs/using.

**Comment by shakteebiswal** [comment]
I tried the command. Here's the screenshot of the output:

![Screenshot_1](https://user-images.githubusercontent.com/77882155/107881608-09858200-6f0b-11eb-817e-e2540c7dd3a0.png)

Yes, I am from India and using Jio as my ISP. I tried changing my DNS to Google's but still the error persists.

**Comment by kzidane** [comment]
@shakteebiswal sounds like a DNS issue on your end. You should probably reach out to your ISP about this issue. In the meantime, using a different DNS might help. See https://developers.google.com/speed/public-dns/docs/using.
