### ISSUE TITLE
IDE is not working for me

### ISSUE THREAD

**Issue by pifagor20** [cs50/v4-issues#59]
#### What symptom did you see (attaching screenshots as necessary)?
![Screenshot 2021-04-03 at 23 45 39](https://user-images.githubusercontent.com/58273961/113491076-b5445a80-94d6-11eb-9acd-a438c972f66f.png)

#### When date and time (UTC) did the problem happen?
20:40 UTC
#### What steps did you follow to reproduce the problem?
1 Reloaded the page
2 Exited out and tried again
#### Which web browser did you use (including version number)?
Google Chrome is up to date
Version 89.0.4389.114 (Official Build) (x86_64)
#### Which operating system did you use (including version number)?
macOS Catalina version 10.15.7
#### Did you log in to CS50 IDE using the same GitHub account you used to create this issue?
yes

**Comment by kzidane** [comment]
If you open Chrome's console by pressing Ctrl + Shift + J, do you see any errors in the console when you get this error?

**Comment by pifagor20** [comment]
<img width="1680" alt="Screenshot 2021-04-04 at 09 50 31" src="https://user-images.githubusercontent.com/58273961/113501035-34637e00-952b-11eb-9a2f-cc34441ea687.png">
Hi,
Yes, I am getting 502 Bad Gateway error

**Comment by kzidane** [comment]
Try again now?

**Comment by pifagor20** [comment]
It is working!
<img width="1680" alt="Screenshot 2021-04-04 at 15 54 10" src="https://user-images.githubusercontent.com/58273961/113509403-09dee880-955e-11eb-90d7-5d4c9dbeaf38.png">
Thank you a lot!😍💪

**Comment by davkct** [comment]
I'm having the same problem 
![image](https://user-images.githubusercontent.com/36538944/162623560-19dec0ac-61c0-4f53-af72-af9a86ba8fd8.png)

**Comment by rongxin-liu** [comment]
> davkct

Please try visiting code.cs50.io again now and see if that works?

**Comment by davkct** [comment]
Yes, it is working now but there's a problem:

![image](https://user-images.githubusercontent.com/36538944/162640047-21e7c5d1-4efa-40a6-b15a-9ad0935f653c.png)
![image](https://user-images.githubusercontent.com/36538944/162640139-ab3946b9-9af5-46c2-a94b-b1139dafb9da.png)

The letters are completely messed up
Do you know how to fix it?

**Comment by davkct** [comment]
Apparently it was my browser, changed to chrome and was fine then. Thanks

**Comment by mcaloianu** [comment]
Hi, I'm having the same problem
![Screenshot (120)](https://user-images.githubusercontent.com/90765387/162736583-9a7331e3-9bb1-4825-ad2b-cb23dfdcb0e4.png)
 here

**Comment by nathwood** [comment]
Hi CS50 Team, I am having the same "Bad Gateway" issue with creating a repository.

I have already allowed all permissions to the CS50 course via my GitHub account.

![220411 Bad gateway](https://user-images.githubusercontent.com/66220429/162798732-5ef578c8-b056-4e50-9112-b08d35dfde57.PNG)
.

--[UPDATE]--
I fixed this by switching browser from Chrome to Edge. I was able to get into the IDE afterwards.

**Comment by johnseabird** [comment]
Same issue - switching browsers does not help unfortunately

**Comment by iTzVoko** [comment]
I have the same issue, I try to back to code.cs50.io doesn't work.

**Comment by rongxin-liu** [comment]
> I have the same issue, I try to back to code.cs50.io doesn't work.

Please email sysadmins@cs50.harvard.edu and be specific about your issue.

**Comment by davkct** [comment]
Thank you, I've solved

**Comment by willise414** [comment]
Hello

I also receive a 502 Bad Gateway - could not create repo. Please try again in 5-10 minutes. I have also tried to open in VS Code Desktop with the same result.

Thank you for any support to remedy.

**Comment by leexizhe** [comment]
Hello, i having the same issue.

**Comment by DvaDvaD** [comment]
hello

I received a similar issue showing Bad Gateway-Could not add as collaborator
please help

**Comment by CodeMeLater** [comment]
Hello, same issue for me :(

**Comment by dmalan** [comment]
Apologies, do keep an eye on https://cs50.statuspage.io/incidents/fmgc736bd132!

**Comment by Iskren201** [comment]
Hello i have the same problem , how i can fix it  ?

**Comment by hansonth12** [comment]
I have the same problem :( tried to follow different tutorials and logging in and out of my github account, as well as restarting chrome but still says bad gateway. What should I do?

**Comment by rongxin-liu** [comment]
> I have the same problem :( tried to follow different tutorials and logging in and out of my github account, as well as restarting chrome but still says bad gateway. What should I do?

Please email sysadmins@cs50.harvard.edu about it!

**Comment by shw06** [comment]
same problem. tried logging out and log in again.
