### ISSUE TITLE
My ~./bashrc aliasbuilder nerfed the terminal loading

### ISSUE THREAD

**Issue by 09jlardinois** [cs50/v4-issues#6]
#### What symptom did you see (attaching screenshots as necessary)?
Loading a terminal threw an error as it tried to find an alias "cp" to unalias.
I called unalias cp through my aliasbuilder file that I ran as source in bashrc. 
Apparently cp -i doesn't exist as an alias anymore, so it could not find it and resulted in an infinite loop on terminal load. Essentially, I couldn't use the terminal to change the bashrc (although I found an alternative by overwriting), but even then, overwriting didn't work because c9 kept trying the oldest configuration. 

Photo attached.
![aliasbuilder error](https://user-images.githubusercontent.com/12178808/52420639-110e2700-2ab8-11e9-9584-f1d6a3286a90.jpg)

#### When date and time (UTC) did the problem happen?
3:09PM UTC

#### What steps did you follow to reproduce the problem?
1. create a file called "aliasbuilder" (plain text, no extension) with the first line, "unalias cp"
2. run it as source from ~/.bashrc
3. load a new terminal

#### Which web browser did you use (including version number)?
Chrome Version 72.0.3626.96 (Official Build) (64-bit)

#### Which operating system did you use (including version number)?
Win 10 x64 Pro
Version	10.0.17763 Build 17763

#### Did you log in to CS50 IDE using the same GitHub account you used to create this issue?
Yes

**Comment by kzidane** [comment]
Breaking `.bashrc` may break your IDE. `.bashrc` no longer persists, so restarting the IDE should fix.
