### ISSUE TITLE
CS50 IDE failing to launch

### ISSUE THREAD

**Issue by KhathutsheloMakatu** [cs50/v4-issues#60]
I am attempting to complete my task and my IDE is taking long to load, after few minutes it states that it has failed to load. When I check the console, this appears:![image](https://user-images.githubusercontent.com/71704227/116745024-1dfdf480-a9fb-11eb-8544-ac89035bd25b.png)
Help please 🤝

**Comment by kzidane** [comment]
Hi @KhathutsheloMakatu! Is this issue persisting for you if you try again now?

**Comment by KhathutsheloMakatu** [comment]
Hello, My IDE successfully loads and the issue of not loading has stopped. Thank you very much.
