### ISSUE TITLE
ide is not recognizing my semi colon

### ISSUE THREAD

**Issue by Beasttype13** [cs50/v4-issues#61]
#### What symptom did you see (attaching screenshots as necessary)?
Everytime I make population it says error and asks me did I put a semi colon at the end of line 9. Which I keep doing and it keeps giving me the same error message

#### When date and time (UTC) did the problem happen?
Tuesday 5/11/2021 at 5:45 pm

#### What steps did you follow to reproduce the problem?
1. step 1
1. step 2
1. step 3

#### Which web browser did you use (including version number)?
Both microsoft edge and chrome

#### Did you log in to CS50 IDE using the same GitHub account you used to create this issue?
yes

Asking for help...

dog.c:6:12: error: expected ';' at end of declaration
  int start size = get_int ("start size:);
           ^
           ;

Are you missing a semicolon at the end of line 6 of dog.c?

**Comment by dmalan** [comment]
You seem to be missing a double quote!

**Comment by Beasttype13** [comment]
#include <cs50.h>
#include <stdio.h>

int main (void)

{
    //TODO:Prompt user for start size
    
    int start size = get_int("start size:");
    
   
}   
    Thank you for responding. No, here is the code where else does there need to be a double quote?
I still get this error
1 error generated.
make: *** [<builtin>: population] Error 1

Asking for help...

population.c:9:14: error: expected ';' at end of declaration
    int start size = get_int("start size:");
             ^
             ;

Are you missing a semicolon at the end of line 9 of population.c?
~/ $

**Comment by dmalan** [comment]
`start size` isn't a valid variable name, as it has a space!

**Comment by Beasttype13** [comment]
Owww success!!! God Bless You! 
#include <cs50.h>
#include <stdio.h>

int main (void)

{
    
    
    int n = get_int("start size:");
    
    printf ("start size ,");
    
$ make population
clang -ggdb3 -O0 -std=c11 -Wall -Werror -Wextra -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wshadow    population.c  -lcrypt -lcs50 -lm -o population
~/ $ ./population
start size:
