### ISSUE TITLE
Cannot access CS50 IDE

### ISSUE THREAD

**Issue by LordDeadPunch** [cs50/v4-issues#63]
I cannot access cs50 ide. I tried to continue the course but when I open the link it keeps loading and after a long time in the loading state it says that it was not possible to make the connection. (attached photo)
I tried to solve it by deleting cookies and cache, using incognito mode, using other browsers and even trying to enter from another device. Nothing worked

#### What symptom did you see (attaching screenshots as necessary)?
![image](https://user-images.githubusercontent.com/72292626/126120876-6567dc7e-1ef3-476b-9e7d-c8c86cd59f81.png)
![image](https://user-images.githubusercontent.com/72292626/126120955-468e41a6-215c-47ca-a52d-445c0fc5ec8b.png)

#### When date and time (UTC) did the problem happen?
07-18-2021

#### What steps did you follow to reproduce the problem?
1. step 1 Enter the link to cs50 ide 
1. step 2 Try to connect
1. step 3 Wait 4-5 minutes until you get the error like the one in the picture. 

#### Which web browser did you use (including version number)?
Google Chrome Version 91.0.4472.164 (Official Build) (64-bit)
#### Which operating system did you use (including version number)?
Windows 10
#### Did you log in to CS50 IDE using the same GitHub account you used to create this issue?
Yes

**Comment by kzidane** [comment]
Hi @LordDeadPunch! Could you please give it another try and let us know if the issue is persisting?

**Comment by LordDeadPunch** [comment]
I was able to log in, thanks :D

**Comment by Josef-13** [comment]
> Hi @LordDeadPunch! Could you please give it another try and let us know if the issue is persisting?

i have the same problem
what should i do??

**Comment by rongxin-liu** [comment]
ide.cs50.io has been deprecated. Please use code.cs50.io instead.
