### ISSUE TITLE
deleted /ubuntu directory now unable to access ide

### ISSUE THREAD

**Issue by m0hi1** [cs50/v4-issues#65]
### I deleted some of /ubuntu files from terminal after login there following issues are happening
![Screenshot (2)](https://user-images.githubusercontent.com/90983768/137849803-84381d7a-ee92-40c7-9380-11d7cef13c9e.png)
![Screenshot (3)](https://user-images.githubusercontent.com/90983768/137849819-e1842680-6471-43a7-a9fa-2f7228292498.png)
![Screenshot (4)](https://user-images.githubusercontent.com/90983768/137849828-9a629db2-0914-4614-bcd0-5c7fdd788fbd.png)

![Screenshot (5)](https://user-images.githubusercontent.com/90983768/137849837-6b670f39-025a-4bd2-9844-e0ad515ada44.png)
![Screenshot (6)](https://user-images.githubusercontent.com/90983768/137849854-1408d5fe-8f63-4d8d-86e7-0ab313016bcb.png)

**Comment by rongxin-liu** [comment]
Thanks for reporting. In this case, CS50 IDE will recover itself.
