### ISSUE TITLE
CS50 IDE is slow, not working

### ISSUE THREAD

**Issue by liamsky42** [cs50/v4-issues#66]
Often seeing "reconnecting" message
Often seeing "file changed. reload?" message
Typing in the console seems stuck, does not react.

Happens on 2021-11-04

#### Which web browser did you use (including version number)?
Brave Version 1.31.88 Chromium: 95.0.4638.69 (Official Build) (64-bit)

#### Which operating system did you use (including version number)?
Windows 11

#### Did you log in to CS50 IDE using the same GitHub account you used to create this issue?
yes

**Comment by rongxin-liu** [comment]
Where are you located? Could you please send us screenshots of the issue?

**Comment by liamsky42** [comment]
Israel

In the evening I see this message:
![image](https://user-images.githubusercontent.com/90472540/140414199-93d33b29-da14-41d3-9ead-a931ad8fe0fa.png)

And this appears at the top:
![image](https://user-images.githubusercontent.com/90472540/140422343-30b69f04-4f18-4fbc-aab5-8b5963d222b6.png)

**Comment by liamsky42** [comment]
Typing in the console seems to be stuck, nothing is echoing for a very long time

**Comment by rongxin-liu** [comment]
Could you please try using Google Chrome and see if you're experiencing the same issue?

**Comment by danielbrito91** [comment]
It is not working for me too. Console shows "net::ERR_EMPTY_RESPONSE"

![image](https://user-images.githubusercontent.com/48222764/140611386-e58bc4d5-295e-4598-84f1-f7071703a77a.png)

**Comment by liamsky42** [comment]
I'm using Brave browes - should be very similar.

**Comment by liamsky42** [comment]
Also:
![image](https://user-images.githubusercontent.com/90472540/140613150-d95e1603-8c29-4514-9d52-dbe7487cb8c6.png)

![image](https://user-images.githubusercontent.com/90472540/140613169-b6251c35-2441-49fb-93ee-6f96774e69f4.png)

**Comment by liamsky42** [comment]
![image](https://user-images.githubusercontent.com/90472540/140614304-5879a079-5e72-41d8-81df-5723d308ef4b.png)

**Comment by liamsky42** [comment]
Haven't checked for several days.
Today it's working well.
