### ISSUE TITLE
Cannot open CS50 ide

### ISSUE THREAD

**Issue by jjooyyccee3** [cs50/v4-issues#67]
#### What symptom did you see (attaching screenshots as necessary)?
![image](https://user-images.githubusercontent.com/93205268/152951346-355ad34b-0cf9-4d26-ac27-e7de5d14823f.png)

#### When date and time (UTC) did the problem happen?
2022/ 2/ 8 04:51
#### What steps did you follow to reproduce the problem?
1. step 1 close the screen shader.
1. step 2 reload the website.
1. step 3 reopen the website in another browser.

#### Which web browser did you use (including version number)?
Google Chrome 97.0.4692.99
#### Which operating system did you use (including version number)?
Window 10
#### Did you log in to CS50 IDE using the same GitHub account you used to create this issue?
yes

**Comment by rongxin-liu** [comment]
Thank you for reporting, we have reached out via email separately.
