### ISSUE TITLE
502 Bad Gateway - Could not create repo

### ISSUE THREAD

**Issue by johnseabird** [cs50/v4-issues#69]
Getting a Bad Gateway error when authenticating with Github. Access is granted via github. After allowing access, the redirect gives me the 502.

**Comment by forukotan** [comment]
i have this issue two please tag me in a solution

**Comment by johnseabird** [comment]
> i have this issue two please tag me in a solution

not sure what was the reason, after following every step in the manual regarding the authentication process, everything worked out of the blue. fingers crossed you solved it!
