### ISSUE TITLE
Can't log in vsc via Github 502 Bad Gateway "Could not add as collaborator"

### ISSUE THREAD

**Issue by Amachirin102** [cs50/v4-issues#72]
#### What symptom did you see (attaching screenshots as necessary)?
When I tried to login Code.cs50.io using Github, it kept showing 502 Bad Gateway Could not add as collaborator 
#### When date and time (UTC) did the problem happen?
Since 6-10-2022 8PM 
#### What steps did you follow to reproduce the problem?
1. CLICK code.cs50.io 
2. CLICK Login via Github 
3. Authorizing to access (oAuth)
4. Error

#### Which web browser did you use (including version number)?
Chrome, Edge and Android device browser 

#### Which operating system did you use (including version number)?
Windows 11 and Android device
#### Did you log in to CS50 IDE using the same GitHub account you used to create this issue?
Yes. My account is in cs50 system on Github too.
![Screenshot_20220611-070738_Chrome](https://user-images.githubusercontent.com/106795917/173185860-3a4fd85d-a851-4208-9174-9e601f27425b.jpg)

**Comment by dmalan** [comment]
Apologies, do keep an eye on https://cs50.statuspage.io/incidents/fmgc736bd132!
