### ISSUE TITLE
code.cs50.io is returning a 502 Bad Gateway error

### ISSUE THREAD

**Issue by BrianMWright** [cs50/v4-issues#74]
#### What symptom did you see (attaching screenshots as necessary)?
"Bad Gateway
Could not create codespace"

#### When date and time (UTC) did the problem happen?
Yesterday, June 22nd.

#### What steps did you follow to reproduce the problem?
1. I deleted my codespaces.
1. Now when I try to re-enable them / resume the course, I get a 502 bad gateway error.

#### Which web browser did you use (including version number)?
Latest Chrome, Firefox, Safari. 
#### Which operating system did you use (including version number)?
Mac OS X 12.4 as well as Windows 10
#### Did you log in to CS50 IDE using the same GitHub account you used to create this issue?
Yes

**Comment by rongxin-liu** [comment]
Please accept the invitation to rejoin `code50`, then try again.

**Comment by BrianMWright** [comment]
Thank you so much, that worked. Can you also send me the invite to access the check50 and style50 as well ? For some reason, I never got the email to accept the access (or I may have missed it).

Update: Everything is working now, thanks again!

**Comment by rongxin-liu** [comment]
> Thank you so much, that worked. Can you also send me the invite to access the check50 and style50 as well ? For some reason, I never got the email to accept the access (or I may have missed it).
> 
> Update: Everything is working now, thanks again!

If you were able to access https://submit.cs50.io, you should be all set. If you are still having issues with check50/submit50, please email sysadmins@cs50.harvard.edu.
