### ISSUE TITLE
Unable to load CS50 IDE

### ISSUE THREAD

**Issue by mcelik19** [cs50/v4-issues#76]
#### What symptom did you see (attaching screenshots as necessary)?
![image](https://user-images.githubusercontent.com/71887162/191566784-28ce8e68-d7d6-4741-a9d4-f9f335d9d9c4.png)

#### When date and time (UTC) did the problem happen?
09-21-2022

#### What steps did you follow to reproduce the problem?
1.step 1 Enter the link to cs50 ide
2.step 2 Try to connect
3.step 3 Wait 4-5 minutes until you get the error like the one in the picture.

#### Which web browser did you use (including version number)?
Google Chrome Version 105.0.5195.127 (Official Build) (64-bit)

#### Which operating system did you use (including version number)?
Windows 10 Pro

#### Did you log in to CS50 IDE using the same GitHub account you used to create this issue?
Yes

**Comment by rongxin-liu** [comment]
We are deprecating ide.cs50.io. Please use [code.cs50.io](https://code.cs50.io) instead

**Comment by mcelik19** [comment]
Will my files back in CS50 IDE be in code.cs50.io ?

**Comment by rongxin-liu** [comment]
You could try downloading them from your legacy CS50 IDE.

**Comment by mcelik19** [comment]
Ok, thanks.
